name: Terraform Azure Deploy

on:
  workflow_call:
    inputs:
      sql_server_name:
        required: true
        type: string
      database_name:
        required: true
        type: string
      location:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environments/sandbox

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve \
          -var="sql_server_name=${{ inputs.sql_server_name }}" \
          -var="database_name=${{ inputs.database_name }}" \
          -var="location=${{ inputs.location }}"
